# permissions for end users to edit kirillapps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: controller
    app.kubernetes.io/managed-by: kustomize
  name: kirillapp-editor-role
rules:
- apiGroups:
  - apps.kubernetesoperator.atwebpages.com
  resources:
  - kirillapps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.kubernetesoperator.atwebpages.com
  resources:
  - kirillapps/status
  verbs:
  - get
