# permissions for end users to view kirillapps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: controller
    app.kubernetes.io/managed-by: kustomize
  name: kirillapp-viewer-role
rules:
- apiGroups:
  - apps.kubernetesoperator.atwebpages.com
  resources:
  - kirillapps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps.kubernetesoperator.atwebpages.com
  resources:
  - kirillapps/status
  verbs:
  - get
