apiVersion: apps.kubernetesoperator.atwebpages.com/v1
kind: KirillApp
metadata:
  labels:
    app.kubernetes.io/name: controller
    app.kubernetes.io/managed-by: kustomize
  name: kirillapp-sample
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kirillapp
  template:
    metadata:
      labels:
        app: kirillapp
    spec:
      containers:
        - name: kirillapp-sample
          image: kyesikov/radio:latest
          ports:
            - containerPort: 3000
  #
  #
  #
  # O(user): Add fields here
