apiVersion: v1
kind: Service
metadata:
    name: radio-service
spec:
  selector:
    app.kubernetes.io/name: controller
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer      
